import type { Metadata } from "next";
import "./globals.css";
import Providers from "./utils/Providers";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Role Based Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
